name: helper
author: Luck
version: ${project.version}
api-version: 1.16
description: ${project.description}
main: me.lucko.helper.internal.StandalonePlugin
website: https://github.com/lucko/helper
load: STARTUP
softdepend: [ProtocolLib, Citizens, ViaVersion]