name: helper-sql
author: Luck
version: ${project.version}
api-version: 1.16
description: ${project.description}
main: me.lucko.helper.sql.plugin.HelperSqlPlugin
website: https://github.com/lucko/helper
load: STARTUP
depend: [helper]