name: helper-profiles
author: Luck
version: ${project.version}
api-version: 1.16
description: ${project.description}
main: me.lucko.helper.profiles.plugin.HelperProfilesPlugin
website: https://github.com/lucko/helper
load: STARTUP
depend: [helper, helper-sql]